### ISSUE TITLE
Implement `liberty get`

### ISSUE THREAD

**Issue by CuriousCain** [liberty-org/cli#10]
Example:
<code>liberty get github.com/liberty-org/cli</code>

EDIT [Revised]:
<code>liberty get github:liberty-org/cli</code>

To install a single package.
Should be added to liberty.json.

**Comment by justjoeyuk** [comment]
@CuriousCain or `liberty get github:liberty-org/cli` with the provider format

**Comment by CuriousCain** [comment]
Yeah, that works.
