### ISSUE TITLE
Implement `liberty help`

### ISSUE THREAD

**Issue by justjoeyuk** [liberty-org/cli#3]
The `liberty help` command should print a basic overview of the core commands and their purpose. We will improve this in the future but for an early version, this should do. The help command should print to the standard output and contain similar text to:

******Liberty Help******

**liberty init**
Initializes your project with a liberty file. If you provide the tool with additional information, it will enable other developers to find your code using our website. However, we don't store anything more than we ask.

**liberty install**
Downloads and installs any dependencies in your liberty file. The "lib" dependencies will be installed in a directory names `_libs` at the root of your project.

**liberty update**
Updates liberty to the latest stable version.

**liberty get {p}**
Downloads and installs the lib/binary. E.g `liberty get github:liberty-org/cli`
- p: the package alias

**liberty version**
Displays the version that is in the $PATH. Also displays the build architecture.

**liberty list**
Displays a list of the installed packages and their versions. Also displays whether they are "binary" dependencies or "lib" dependencies.

**Comment by barthr** [comment]
I would like to implement this, are there any guidelines on how U would like it?

**Comment by justjoeyuk** [comment]
@barthr Hi, thanks for getting involved so early on! I'll update the issue comment to represent how it should appear. It's up to you if you want to add any special formatting!

Cheers,
Joey

**Comment by CuriousCain** [comment]
We will peer review code, too, so if any improvement suggestions are put forward; we'll discuss the proposed changes. :-)

**Comment by justjoeyuk** [comment]
@barthr You happy going ahead with this?

**Comment by barthr** [comment]
Yes I would love to make it!

**Comment by barthr** [comment]
I'm done but how can I push my changes to this repo, I've tried to create a pull request but it wont let me on master branch

**Comment by CuriousCain** [comment]
You should fork the repo, make the changes in your forked repo and then make a pull request between the two.
