### ISSUE TITLE
No breaking tests in master branch

### ISSUE THREAD

**Issue by CuriousCain** [liberty-org/cli#9]
Can I propose that tests are never breaking in the master branch, please.

We should use local branches for feature development and merge into master only when tests pass.

This is after a fresh pull:
![image](https://cloud.githubusercontent.com/assets/1616199/14060540/9e237a34-f35f-11e5-82b9-02d82428975c.png)

Otherwise we will suddenly find that our code does not work, as above.

**Comment by justjoeyuk** [comment]
:+1: @EwanValentine ?

**Comment by EwanValentine** [comment]
Was that in master? It should've already been in its own branch

**Comment by CuriousCain** [comment]
@EwanValentine It got merged in with commit c964babff83792142ad4d99437d6e30ce0e8ab15

**Comment by justjoeyuk** [comment]
In the future, we should ensure that `go test` passes before any pull requests are made towards master. We should avoid committing straight into master as much as we can from now. If it's a failure on a HTTP request, investigate why and if it's beyond our control, pull request it up! :smile:
